### JSON output:
# { name: hello_world,
#   on: [push],
#   jobs: {}
# }

# name
name: hello_world

# trigger
on: ## on is an array
- push

# one or more jobs
jobs: ## jobs are run sequentially
  greetings:
    runs-on: ubuntu-latest
    steps: 
    - id: s00 #id each step
      #running some shell bash command
      run: echo "Current time in GitHub is $(date), ${GITHUB_OUTPUT}" #works like Python f-strings

    - id: s01
    # create a value and pass to the next step
      run: echo "CURR_DATE=$(date)" >> $GITHUB_OUTPUT
      ## >> means append to the file, > means replace everything

    - id: s02 #use prebuilt actions
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'moo moo moo'
        color: 'red'

    # - id: s01
    #   run: ls -al
    # - id: s02 <-- ERROR here!!
    #   run: cat hello.txt

  goodbye: # group jobs logically

    runs-on: ubuntu-latest
    steps:
    - id: s03
      run: echo "Goodbye from GitHub Actions!"