### JSON output:
# { name: hello_world,
#   on: [push],
#   jobs: {}
# }

# name
name: hello_world

# trigger
on: ## on is an array
- push

# one or more jobs
jobs: ## jobs are run sequentially
  greetings:
    runs-on: ubuntu-latest
    steps: 
    - id: s00 #id each step
      #running some shell bash command
      run: echo "Current time in GitHub is $(date)" #works like Python f-strings
  goodbye: # group jobs logically

    runs-on: ubuntu-latest
    steps:
    - id: s01
      run: echo "Goodbye from GitHub Actions!"